name: Sync Files to roxiestreams.live

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace domain before sync
        run: |
          find . -type f -name '*.html' -exec sed -i 's/roxiestreams.cc/roxiestreams.live/g' {} +

      - name: Sync to roxiestreams.live repo
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.PAT }}
          CONFIG_PATH: .github/sync.yml
          IS_FINE_GRAINED: false
