name: Sync files to roxiestreams.live

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace roxiestreams.cc with roxiestreams.live in files
        run: |
          find . -type f -name '*.html' -exec sed -i 's/roxiestreams.cc/roxiestreams.live/g' {} +

      - name: Sync files to roxiestreams.live repo
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          destination_repo: roxxie09/roxxiestreams.live
          destination_branch: main
          github_token: ${{ secrets.PAT }}
          folder_to_sync: '.'
          commit_message: 'Sync roxiestreams.cc to roxiestreams.live with domain replace'
